USE [CSIS360]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [agency].[SOURCE_OF_APPN_AGENCY](
	[SOURCE_OF_APPN_AGENCY] [varchar](28) NULL,
	[treasuryagencycode] [varchar](2) NULL,
	[CSIScreatedDate] [datetime2](7) NOT NULL,
	[CSISmodifiedDate] [datetime2](7) NOT NULL,
	[CSISmodifiedBy] [nvarchar](128) NOT NULL,
	[FundingAgencyID] [varchar](4) NULL,
	[ImplementingAgencyID] [varchar](4) NULL
)

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [agency].[SOURCE_OF_APPN_AGENCY] ADD  CONSTRAINT [DF__SOURCE_OF__CSISc__2AB62B09]  DEFAULT (getdate()) FOR [CSIScreatedDate]
GO
ALTER TABLE [agency].[SOURCE_OF_APPN_AGENCY] ADD  CONSTRAINT [DF__SOURCE_OF__CSISm__2BAA4F42]  DEFAULT (getdate()) FOR [CSISmodifiedDate]
GO
ALTER TABLE [agency].[SOURCE_OF_APPN_AGENCY] ADD  CONSTRAINT [DF__SOURCE_OF__CSISm__2C9E737B]  DEFAULT (suser_sname()) FOR [CSISmodifiedBy]
GO
ALTER TABLE [agency].[SOURCE_OF_APPN_AGENCY]  WITH NOCHECK ADD  CONSTRAINT [FK__SOURCE_OF__Fundi__2D9297B4] FOREIGN KEY([FundingAgencyID])
REFERENCES [FPDSTypeTable].[AgencyID] ([AgencyID])
GO
ALTER TABLE [agency].[SOURCE_OF_APPN_AGENCY] CHECK CONSTRAINT [FK__SOURCE_OF__Fundi__2D9297B4]
GO
ALTER TABLE [agency].[SOURCE_OF_APPN_AGENCY]  WITH NOCHECK ADD  CONSTRAINT [FK__SOURCE_OF__Imple__2E86BBED] FOREIGN KEY([ImplementingAgencyID])
REFERENCES [FPDSTypeTable].[AgencyID] ([AgencyID])
GO
ALTER TABLE [agency].[SOURCE_OF_APPN_AGENCY] CHECK CONSTRAINT [FK__SOURCE_OF__Imple__2E86BBED]
GO
