USE [CSIS360]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [agency].[AgencyNameToAgencyID](
	[AgencyID] [varchar](4) NULL,
	[AgencyName] [nvarchar](255) NULL,
 CONSTRAINT [UQ__AgencyNa__C79F132CDC78667A] UNIQUE NONCLUSTERED 
(
	[AgencyName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
