USE [CSIS360]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [Assistance].[USAIDforwardPartnerType](
	[USAIDforwardPartnerType] [varchar](25) NOT NULL,
	[LocalConfidenceLevel] [int] NULL,
 CONSTRAINT [PK_USAIDforwardType] PRIMARY KEY CLUSTERED 
(
	[USAIDforwardPartnerType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = ON, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
SET ANSI_PADDING OFF
GO
