USE [CSIS360]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [Assistance].[record_type](
	[Unseperated] [varchar](255) NULL,
	[record_type] [varchar](1) NOT NULL,
	[record_type_text] [varchar](24) NULL,
 CONSTRAINT [PK__record_t__828B6F8C418D8392] PRIMARY KEY CLUSTERED 
(
	[record_type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = ON, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
SET ANSI_PADDING OFF
GO
