SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Assistance].[USAIDforwardPartnerType](
	[USAIDforwardPartnerType] [varchar](25) NOT NULL,
	[LocalConfidenceLevel] [int] NULL,
 CONSTRAINT [PK_USAIDforwardType] PRIMARY KEY CLUSTERED 
(
	[USAIDforwardPartnerType] ASC
)WITH (STATISTICS_NORECOMPUTE = ON, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
