SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Assistance].[UCDPactorID](
	[UCDPactorID] [smallint] NOT NULL,
	[Name] [varchar](100) NULL,
	[NameFull] [nvarchar](255) NULL,
	[GeographicISOalpha3] [nvarchar](3) NULL,
 CONSTRAINT [pk_UCDPactorlist] PRIMARY KEY CLUSTERED 
(
	[UCDPactorID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Assistance].[UCDPactorID]  WITH CHECK ADD FOREIGN KEY([GeographicISOalpha3])
REFERENCES [Location].[CountryCodes] ([alpha-3])
GO
