SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [budget].[Fund_Type](
	[Fund_Type] [varchar](4) NOT NULL,
	[Fund_Type_Description] [varchar](35) NULL,
 CONSTRAINT [pk_Fund_Type] PRIMARY KEY CLUSTERED 
(
	[Fund_Type] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
