SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [budget].[ColorOfMoney](
	[ColorOfMoney] [varchar](7) NOT NULL,
 CONSTRAINT [pk_ColorOfMoney] PRIMARY KEY CLUSTERED 
(
	[ColorOfMoney] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
