SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [budget].[SOURCE_OF_APPN_SYMBOL](
	[SOURCE_OF_APPN_AGENCY] [varchar](28) NOT NULL,
	[SOURCE_OF_APPN_SYMBOL] [varchar](6) NOT NULL,
	[treasuryagencycode] [smallint] NOT NULL,
	[APPN_ACCOUNT] [varchar](40) NULL,
	[mainaccountcode] [smallint] NOT NULL,
 CONSTRAINT [PK_SOURCE_OF_APPN_SYMBOL_SOURCE_OF_APPN_AGENCY] PRIMARY KEY CLUSTERED 
(
	[SOURCE_OF_APPN_SYMBOL] ASC,
	[SOURCE_OF_APPN_AGENCY] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [budget].[SOURCE_OF_APPN_SYMBOL]  WITH NOCHECK ADD  CONSTRAINT [FK_budget_SOURCE_OF_APPN_SYMBOL_treasuryagencycode_mainaccountcode] FOREIGN KEY([treasuryagencycode], [mainaccountcode])
REFERENCES [budget].[MainAccountCode] ([TreasuryAgencyCode], [MainAccountCode])
GO
ALTER TABLE [budget].[SOURCE_OF_APPN_SYMBOL] CHECK CONSTRAINT [FK_budget_SOURCE_OF_APPN_SYMBOL_treasuryagencycode_mainaccountcode]
GO
