SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [budget].[JBookHeader](
	[JBookHeader] [varchar](50) NOT NULL,
	[IsRevisedJBook] [bit] NULL,
 CONSTRAINT [Budget_JBookHeader] PRIMARY KEY CLUSTERED 
(
	[JBookHeader] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
