SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [budget].[CostType](
	[CostType] [varchar](1) NOT NULL,
	[CostTypeTitle] [varchar](44) NULL,
 CONSTRAINT [pk_budget_costType] PRIMARY KEY CLUSTERED 
(
	[CostType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
