SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [budget].[Type](
	[Type] [varchar](4) NOT NULL,
	[Exhibits] [varchar](13) NULL,
 CONSTRAINT [pk_Budget_Type] PRIMARY KEY CLUSTERED 
(
	[Type] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [budget].[Type]  WITH CHECK ADD  CONSTRAINT [chk_Budget_Type] CHECK  (([Type]<>''))
GO
ALTER TABLE [budget].[Type] CHECK CONSTRAINT [chk_Budget_Type]
GO
