SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [budget].[rec_flag](
	[rec_flag] [varchar](4) NOT NULL,
	[IsARRA] [bit] NULL,
 CONSTRAINT [pk_rec_flag] PRIMARY KEY CLUSTERED 
(
	[rec_flag] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
