SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [budget].[JBookHeader](
	[JBookHeader] [varchar](50) NOT NULL,
	[IsRevisedJBook] [bit] NULL,
 CONSTRAINT [Budget_JBookHeader] PRIMARY KEY CLUSTERED 
(
	[JBookHeader] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
