SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [budget].[CostType](
	[AccountDSI] [varchar](5) NOT NULL,
	[CostType] [varchar](1) NOT NULL,
	[CostTypeTitle] [varchar](44) NULL,
 CONSTRAINT [pk_CostType] PRIMARY KEY CLUSTERED 
(
	[AccountDSI] ASC,
	[CostType] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [budget].[CostType]  WITH NOCHECK ADD  CONSTRAINT [FK__CostType__Accoun__60B3145E] FOREIGN KEY([AccountDSI])
REFERENCES [budget].[AccountDSI] ([AccountDSI])
GO
ALTER TABLE [budget].[CostType] CHECK CONSTRAINT [FK__CostType__Accoun__60B3145E]
GO
