SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [budget].[Acct_Type](
	[Acct_Type] [varchar](5) NOT NULL,
	[Acct_Type_Description] [varchar](22) NULL,
	[IsOffsetAccount] [bit] NULL,
 CONSTRAINT [pk_Acct_Type] PRIMARY KEY CLUSTERED 
(
	[Acct_Type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
