SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [budget].[Classified](
	[Classified] [varchar](1) NOT NULL,
 CONSTRAINT [pk_Budget_Classified] PRIMARY KEY CLUSTERED 
(
	[Classified] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
