SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [budget].[ColorOfMoney](
	[ColorOfMoney] [varchar](7) NOT NULL,
 CONSTRAINT [pk_ColorOfMoney] PRIMARY KEY CLUSTERED 
(
	[ColorOfMoney] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
