SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [budget].[IDcode](
	[IDcode] [varchar](1) NOT NULL,
 CONSTRAINT [pk_Budget_IDcode] PRIMARY KEY CLUSTERED 
(
	[IDcode] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [budget].[IDcode]  WITH CHECK ADD  CONSTRAINT [chk_Budget_IDcode] CHECK  (([IDcode]<>''))
GO
ALTER TABLE [budget].[IDcode] CHECK CONSTRAINT [chk_Budget_IDcode]
GO
