SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [budget].[Acct_Type](
	[Acct_Type] [varchar](5) NOT NULL,
	[Acct_Type_Description] [varchar](22) NULL,
	[IsOffsetAccount] [bit] NULL,
 CONSTRAINT [pk_Acct_Type] PRIMARY KEY CLUSTERED 
(
	[Acct_Type] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
