USE [CSIS360]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [budget].[SubFunctionCode](
	[SubfunctionCode] [smallint] NOT NULL,
	[agencyid] [varchar](4) NULL,
	[SubfunctionTitle] [varchar](100) NULL,
 CONSTRAINT [pk_SubFunctionCode] PRIMARY KEY CLUSTERED 
(
	[SubfunctionCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
SET ANSI_PADDING OFF
GO
