USE [CSIS360]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Contract].[GoviniPBLbyDescriptionOrTitle](
	[link] [varchar](78) NULL,
	[Title] [varchar](272) NULL,
	[Sector] [varchar](19) NULL,
	[Opportunity Type] [varchar](26) NULL,
	[Award Type] [varchar](32) NULL,
	[Funding Agency] [varchar](50) NULL,
	[Parent Funding Office] [varchar](76) NULL,
	[Funding Office] [varchar](60) NULL,
	[Contracting Agency] [varchar](35) NULL,
	[Parent Contracting Office] [varchar](76) NULL,
	[Contracting Office] [varchar](60) NULL,
	[Solicitation ID] [varchar](29) NULL,
	[Contract ID] [varchar](15) NULL,
	[Task Order ID] [varchar](25) NULL,
	[Award Number] [varchar](19) NULL,
	[Posted Date] [datetime] NULL,
	[Award Date] [datetime] NULL,
	[Archive Date] [datetime] NULL,
	[Response Date] [datetime] NULL,
	[Start Date] [datetime] NULL,
	[End Date] [datetime] NULL,
	[Estimated Value] [real] NULL,
	[Awarded Value] [real] NULL,
	[Available Amount] [real] NULL,
	[Offers Received] [smallint] NULL,
	[Awardee Name] [varchar](62) NULL,
	[Industry] [varchar](29) NULL,
	[Sub Industry] [varchar](48) NULL,
	[Place Of Performance Address 1] [varchar](42) NULL,
	[Place Of Performance Address 2] [varchar](max) NULL,
	[Place Of Performance City] [varchar](20) NULL,
	[Place Of Performance State] [varchar](2) NULL,
	[Place Of Performance Zip] [int] NULL,
	[Place Of Performance Country] [varchar](13) NULL,
	[NAICS] [varchar](112) NULL,
	[PSC] [varchar](98) NULL,
	[NIGP] [varchar](112) NULL,
	[Set Aside] [varchar](max) NULL,
	[Pricing Type] [varchar](25) NULL,
	[Extent Competed] [varchar](25) NULL,
	[Complexity Score] [smallint] NULL,
	[Agency Address 1] [varchar](42) NULL,
	[Agency Address 2] [varchar](max) NULL,
	[Agency City] [varchar](20) NULL,
	[Agency State] [varchar](2) NULL,
	[Agency Zip] [int] NULL,
	[Agency Phone] [varchar](max) NULL,
	[Agency Fax] [varchar](max) NULL,
	[Agency URL] [varchar](76) NULL,
	[Agency Organization Score] [smallint] NULL,
	[Agency Parent Name] [varchar](35) NULL,
	[Contract Duration] [varchar](9) NULL,
	[Cycle Time] [smallint] NULL,
	[Primary Contact First Name] [varchar](11) NULL,
	[Primary Contact Middle Name] [varchar](7) NULL,
	[Primary Contact Last Name] [varchar](8) NULL,
	[Primary Contact Title] [varchar](19) NULL,
	[Primary Contact Email] [varchar](29) NULL,
	[Primary Contact Phone] [varchar](13) NULL,
	[Primary Contact Fax] [varchar](13) NULL,
	[Awardee Parent Name] [varchar](55) NULL,
	[Awardee Address 1] [varchar](56) NULL,
	[Awardee Address 2] [varchar](max) NULL,
	[Awardee City] [varchar](20) NULL,
	[Awardee State] [varchar](7) NULL,
	[Awardee Zip] [varchar](5) NULL,
	[Awardee Phone] [varchar](max) NULL,
	[Awardee Fax] [varchar](max) NULL,
	[Awardee URL] [varchar](57) NULL,
	[Awardee Organization Score] [smallint] NULL,
	[Awardee Contact First Name] [varchar](max) NULL,
	[Awardee Contact First Name2] [varchar](max) NULL,
	[Awardee Contact Middle Name] [varchar](max) NULL,
	[Awardee Contact Last Name] [varchar](max) NULL,
	[Awardee Contact Title] [varchar](max) NULL,
	[Awardee Contact Email] [varchar](max) NULL,
	[Awardee Contact Phone] [varchar](max) NULL,
	[Awardee Contact Fax] [varchar](max) NULL,
	[Awardee Contact Fax2] [varchar](max) NULL,
	[Description] [varchar](max) NULL,
	[Source URL] [varchar](84) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
