USE [CSIS360]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [Contract].[LPTA2014_11_29](
	[link] [varchar](79) NULL,
	[Title] [varchar](585) NULL,
	[Sector] [varchar](20) NULL,
	[Opportunity Type] [varchar](28) NULL,
	[Award Type] [varchar](38) NULL,
	[Agency Name] [varchar](143) NULL,
	[Rollup Agency Name] [varchar](88) NULL,
	[Solicitation ID] [varchar](75) NULL,
	[Contract ID] [varchar](84) NULL,
	[Posted Date] [datetime] NULL,
	[Award Date] [datetime] NULL,
	[Archive Date] [datetime] NULL,
	[Response Date] [datetime] NULL,
	[Start Date] [datetime] NULL,
	[End Date] [datetime] NULL,
	[Estimated Value] [real] NULL,
	[Awarded Value] [real] NULL,
	[Available Amount] [real] NULL,
	[Offers Received] [smallint] NULL,
	[Awardee Name] [varchar](152) NULL,
	[Industry] [varchar](31) NULL,
	[Sub Industry] [varchar](80) NULL,
	[Place Of Performance Address 1] [varchar](95) NULL,
	[Place Of Performance Address 2] [varchar](max) NULL,
	[Place Of Performance City] [varchar](29) NULL,
	[Place Of Performance State] [varchar](12) NULL,
	[Place Of Performance Zip] [int] NULL,
	[Place Of Performance Country] [varchar](3) NULL,
	[NAICS] [varchar](139) NULL,
	[PSC] [varchar](113) NULL,
	[NIGP] [varchar](139) NULL,
	[Set Aside] [varchar](79) NULL,
	[Pricing Type] [varchar](17) NULL,
	[Extent Competed] [varchar](57) NULL,
	[Complexity Score] [smallint] NULL,
	[Agency Address 1] [varchar](95) NULL,
	[Agency Address 2] [varchar](max) NULL,
	[Agency City] [varchar](28) NULL,
	[Agency State] [varchar](5) NULL,
	[Agency Zip] [int] NULL,
	[Agency Phone] [varchar](15) NULL,
	[Agency Fax] [varchar](max) NULL,
	[Agency URL] [varchar](140) NULL,
	[Agency Organization Score] [smallint] NULL,
	[Agency Parent Name] [varchar](88) NULL,
	[Contract Duration] [varchar](6) NULL,
	[Cycle Time] [smallint] NULL,
	[Primary Contact First Name] [varchar](13) NULL,
	[Primary Contact Middle Name] [varchar](12) NULL,
	[Primary Contact Last Name] [varchar](20) NULL,
	[Primary Contact Title] [varchar](106) NULL,
	[Primary Contact Email] [varchar](49) NULL,
	[Primary Contact Phone] [varchar](25) NULL,
	[Primary Contact Fax] [varchar](16) NULL,
	[Awardee Parent Name] [varchar](152) NULL,
	[Awardee Address 1] [varchar](430) NULL,
	[Awardee Address 2] [varchar](max) NULL,
	[Awardee City] [varchar](22) NULL,
	[Awardee State] [varchar](12) NULL,
	[Awardee Zip] [int] NULL,
	[Awardee Phone] [varchar](13) NULL,
	[Awardee Fax] [varchar](max) NULL,
	[Awardee URL] [varchar](69) NULL,
	[Awardee Organization Score] [smallint] NULL,
	[Awardee Contact First Name] [varchar](9) NULL,
	[Awardee Contact First Name2] [varchar](9) NULL,
	[Awardee Contact Middle Name] [varchar](1) NULL,
	[Awardee Contact Last Name] [varchar](11) NULL,
	[Awardee Contact Title] [varchar](max) NULL,
	[Awardee Contact Email] [varchar](41) NULL,
	[Awardee Contact Phone] [varchar](14) NULL,
	[Awardee Contact Fax] [varchar](13) NULL,
	[Awardee Contact Fax2] [varchar](13) NULL,
	[Source URL] [varchar](134) NULL
)

GO
SET ANSI_PADDING OFF
GO
