USE [CSIS360]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NewPSC](
	[NEW PSC CODE] [nvarchar](255) NULL,
	[NEW SHORT DESCRIPTION] [nvarchar](255) NULL,
	[START DATE] [datetime] NULL
)

GO
