/****** Object:  Table [ErrorLogging].[FPDSdelta]    Script Date: 5/4/2024 11:08:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ErrorLogging].[FPDSdelta](
	[government_furnished_property] [varchar](255) NULL,
	[research] [varchar](255) NULL,
	[last_modified_date] [datetime2](7) NULL,
	[award_id_piid] [varchar](50) NULL,
	[modification_number] [varchar](25) NULL,
	[transaction_number] [bigint] NULL,
	[parent_award_agency_id] [varchar](4) NULL,
	[parent_award_agency_name] [varchar](255) NULL,
	[parent_award_id_piid] [varchar](50) NULL,
	[parent_award_modification_number] [varchar](25) NULL,
	[federal_action_obligation] [decimal](19, 4) NULL,
	[base_and_exercised_options_value] [decimal](19, 4) NULL,
	[base_and_all_options_value] [decimal](19, 4) NULL,
	[action_date] [date] NULL,
	[period_of_performance_start_date] [date] NULL,
	[period_of_performance_current_end_date] [datetime2](7) NULL,
	[period_of_performance_potential_end_date] [datetime2](7) NULL,
	[ordering_period_end_date] [date] NULL,
	[awarding_agency_code] [smallint] NULL,
	[awarding_agency_name] [varchar](255) NULL,
	[awarding_sub_agency_code] [varchar](4) NULL,
	[awarding_sub_agency_name] [varchar](255) NULL,
	[awarding_office_code] [varchar](6) NULL,
	[awarding_office_name] [varchar](255) NULL,
	[funding_agency_code] [varchar](4) NULL,
	[funding_agency_name] [varchar](255) NULL,
	[funding_sub_agency_code] [varchar](4) NULL,
	[funding_sub_agency_name] [varchar](255) NULL,
	[funding_office_code] [varchar](6) NULL,
	[funding_office_name] [varchar](255) NULL,
	[foreign_funding] [varchar](21) NULL,
	[sam_exception] [varchar](1) NULL,
	[recipient_duns] [varchar](13) NULL,
	[recipient_name] [nvarchar](150) NULL,
	[recipient_doing_business_as_name] [nvarchar](150) NULL,
	[recipient_parent_name] [nvarchar](150) NULL,
	[recipient_parent_duns] [varchar](13) NULL,
	[recipient_country_code] [nvarchar](50) NULL,
	[recipient_country_name] [varchar](255) NULL,
	[recipient_address_line_1] [varchar](115) NULL,
	[recipient_address_line_2] [varchar](64) NULL,
	[recipient_city_name] [varchar](35) NULL,
	[recipient_state_code] [varchar](35) NULL,
	[recipient_state_name] [varchar](255) NULL,
	[recipient_zip_4_code] [varchar](28) NULL,
	[prime_award_transaction_recipient_cd_current] [varchar](22) NULL,
	[recipient_phone_number] [varchar](20) NULL,
	[recipient_fax_number] [varchar](30) NULL,
	[primary_place_of_performance_country_code] [varchar](3) NULL,
	[primary_place_of_performance_country_name] [varchar](255) NULL,
	[primary_place_of_performance_city_name] [varchar](100) NULL,
	[primary_place_of_performance_county_name] [varchar](26) NULL,
	[primary_place_of_performance_state_code] [varchar](2) NULL,
	[primary_place_of_performance_state_name] [varchar](255) NULL,
	[primary_place_of_performance_zip_4] [varchar](10) NULL,
	[prime_award_transaction_place_of_performance_cd_current] [varchar](22) NULL,
	[award_type_code] [varchar](1) NULL,
	[award_type] [varchar](255) NULL,
	[idv_type_code] [varchar](1) NULL,
	[idv_type] [varchar](255) NULL,
	[multiple_or_single_award_idv_code] [varchar](1) NULL,
	[multiple_or_single_award_idv] [varchar](255) NULL,
	[type_of_idc_code] [varchar](41) NULL,
	[type_of_idc] [varchar](255) NULL,
	[type_of_contract_pricing_code] [varchar](2) NULL,
	[type_of_contract_pricing] [varchar](255) NULL,
	[transaction_description] [varchar](4035) NULL,
	[action_type_code] [varchar](1) NULL,
	[action_type] [varchar](255) NULL,
	[solicitation_identifier] [varchar](69) NULL,
	[number_of_actions] [bigint] NULL,
	[product_or_service_code] [varchar](4) NULL,
	[product_or_service_code_description] [varchar](512) NULL,
	[contract_bundling_code] [varchar](1) NULL,
	[contract_bundling] [varchar](255) NULL,
	[dod_claimant_program_code] [varchar](3) NULL,
	[dod_claimant_program_description] [varchar](255) NULL,
	[naics_code] [varchar](6) NULL,
	[naics_description] [varchar](255) NULL,
	[recovered_materials_sustainability_code] [varchar](1) NULL,
	[recovered_materials_sustainability] [varchar](255) NULL,
	[domestic_or_foreign_entity_code] [varchar](1) NULL,
	[domestic_or_foreign_entity] [varchar](255) NULL,
	[dod_acquisition_program_code] [varchar](4) NULL,
	[dod_acquisition_program_description] [varchar](255) NULL,
	[information_technology_commercial_item_category_code] [varchar](30) NULL,
	[information_technology_commercial_item_category] [varchar](255) NULL,
	[epa_designated_product_code] [varchar](1) NULL,
	[epa_designated_product] [varchar](255) NULL,
	[country_of_product_or_service_origin_code] [varchar](3) NULL,
	[country_of_product_or_service_origin] [varchar](255) NULL,
	[place_of_manufacture_code] [varchar](1) NULL,
	[place_of_manufacture] [varchar](255) NULL,
	[subcontracting_plan_code] [varchar](1) NULL,
	[subcontracting_plan] [varchar](255) NULL,
	[extent_competed_code] [varchar](3) NULL,
	[extent_competed] [varchar](255) NULL,
	[solicitation_procedures_code] [varchar](5) NULL,
	[solicitation_procedures] [varchar](255) NULL,
	[type_of_set_aside_code] [varchar](10) NULL,
	[type_of_set_aside] [varchar](255) NULL,
	[evaluated_preference_code] [varchar](6) NULL,
	[evaluated_preference] [varchar](255) NULL,
	[research_code] [varchar](3) NULL,
	[fair_opportunity_limited_sources_code] [varchar](4) NULL,
	[fair_opportunity_limited_sources] [varchar](255) NULL,
	[other_than_full_and_open_competition_code] [varchar](3) NULL,
	[other_than_full_and_open_competition] [varchar](255) NULL,
	[number_of_offers_received] [bigint] NULL,
	[simplified_procedures_for_certain_commercial_items_code] [varchar](1) NULL,
	[simplified_procedures_for_certain_commercial_items] [varchar](255) NULL,
	[small_business_competitiveness_demonstration_program] [bit] NULL,
	[commercial_item_acquisition_procedures_code] [varchar](1) NULL,
	[commercial_item_acquisition_procedures] [varchar](255) NULL,
	[a76_fair_act_action_code] [bit] NULL,
	[a76_fair_act_action] [varchar](255) NULL,
	[fed_biz_opps_code] [varchar](1) NULL,
	[fed_biz_opps] [varchar](255) NULL,
	[local_area_set_aside_code] [varchar](4) NULL,
	[local_area_set_aside] [varchar](255) NULL,
	[price_evaluation_adjustment_preference_percent_difference] [smallint] NULL,
	[clinger_cohen_act_planning_code] [bit] NULL,
	[clinger_cohen_act_planning] [varchar](255) NULL,
	[materials_supplies_articles_equipment_code] [varchar](1) NULL,
	[materials_supplies_articles_equipment] [varchar](255) NULL,
	[labor_standards_code] [varchar](1) NULL,
	[labor_standards] [varchar](255) NULL,
	[construction_wage_rate_requirements_code] [varchar](1) NULL,
	[construction_wage_rate_requirements] [varchar](255) NULL,
	[interagency_contracting_authority_code] [varchar](3) NULL,
	[interagency_contracting_authority] [varchar](255) NULL,
	[other_statutory_authority] [varchar](1000) NULL,
	[program_acronym] [varchar](29) NULL,
	[parent_award_type_code] [varchar](1) NULL,
	[parent_award_type] [varchar](255) NULL,
	[parent_award_single_or_multiple_code] [varchar](1) NULL,
	[parent_award_single_or_multiple] [varchar](255) NULL,
	[major_program] [varchar](104) NULL,
	[national_interest_action_code] [varchar](4) NULL,
	[national_interest_action] [varchar](255) NULL,
	[cost_or_pricing_data_code] [varchar](1) NULL,
	[cost_or_pricing_data] [varchar](255) NULL,
	[cost_accounting_standards_clause_code] [varchar](1) NULL,
	[cost_accounting_standards_clause] [varchar](255) NULL,
	[government_furnished_property_code] [varchar](1) NULL,
	[sea_transportation_code] [varchar](1) NULL,
	[sea_transportation] [varchar](255) NULL,
	[undefinitized_action_code] [varchar](1) NULL,
	[undefinitized_action] [varchar](255) NULL,
	[consolidated_contract_code] [varchar](1) NULL,
	[consolidated_contract] [varchar](255) NULL,
	[performance_based_service_acquisition_code] [varchar](38) NULL,
	[performance_based_service_acquisition] [varchar](255) NULL,
	[multi_year_contract_code] [bit] NULL,
	[multi_year_contract] [varchar](255) NULL,
	[contract_financing_code] [varchar](1) NULL,
	[contract_financing] [varchar](255) NULL,
	[purchase_card_as_payment_method_code] [bit] NULL,
	[purchase_card_as_payment_method] [varchar](255) NULL,
	[contingency_humanitarian_or_peacekeeping_operation_code] [varchar](1) NULL,
	[contingency_humanitarian_or_peacekeeping_operation] [varchar](255) NULL,
	[alaskan_native_corporation_owned_firm] [bit] NULL,
	[american_indian_owned_business] [bit] NULL,
	[indian_tribe_federally_recognized] [bit] NULL,
	[native_hawaiian_organization_owned_firm] [bit] NULL,
	[tribally_owned_firm] [bit] NULL,
	[veteran_owned_business] [bit] NULL,
	[service_disabled_veteran_owned_business] [bit] NULL,
	[woman_owned_business] [bit] NULL,
	[women_owned_small_business] [bit] NULL,
	[economically_disadvantaged_women_owned_small_business] [bit] NULL,
	[joint_venture_women_owned_small_business] [bit] NULL,
	[joint_venture_economic_disadvantaged_women_owned_small_bus] [bit] NULL,
	[minority_owned_business] [bit] NULL,
	[subcontinent_asian_asian_indian_american_owned_business] [bit] NULL,
	[asian_pacific_american_owned_business] [bit] NULL,
	[black_american_owned_business] [bit] NULL,
	[hispanic_american_owned_business] [bit] NULL,
	[native_american_owned_business] [bit] NULL,
	[other_minority_owned_business] [bit] NULL,
	[contracting_officers_determination_of_business_size] [varchar](255) NULL,
	[contracting_officers_determination_of_business_size_code] [varchar](1) NULL,
	[emerging_small_business] [bit] NULL,
	[community_developed_corporation_owned_firm] [bit] NULL,
	[labor_surplus_area_firm] [bit] NULL,
	[us_federal_government] [bit] NULL,
	[federally_funded_research_and_development_corp] [bit] NULL,
	[federal_agency] [bit] NULL,
	[us_state_government] [bit] NULL,
	[us_local_government] [bit] NULL,
	[city_local_government] [bit] NULL,
	[county_local_government] [bit] NULL,
	[inter_municipal_local_government] [bit] NULL,
	[local_government_owned] [bit] NULL,
	[municipality_local_government] [bit] NULL,
	[school_district_local_government] [bit] NULL,
	[township_local_government] [bit] NULL,
	[us_tribal_government] [bit] NULL,
	[foreign_government] [bit] NULL,
	[corporate_entity_not_tax_exempt] [bit] NULL,
	[corporate_entity_tax_exempt] [bit] NULL,
	[partnership_or_limited_liability_partnership] [bit] NULL,
	[sole_proprietorship] [bit] NULL,
	[small_agricultural_cooperative] [bit] NULL,
	[international_organization] [bit] NULL,
	[us_government_entity] [bit] NULL,
	[community_development_corporation] [bit] NULL,
	[domestic_shelter] [bit] NULL,
	[educational_institution] [bit] NULL,
	[foundation] [bit] NULL,
	[hospital_flag] [bit] NULL,
	[manufacturer_of_goods] [bit] NULL,
	[veterinary_hospital] [bit] NULL,
	[hispanic_servicing_institution] [bit] NULL,
	[receives_contracts] [bit] NULL,
	[receives_financial_assistance] [bit] NULL,
	[receives_contracts_and_financial_assistance] [bit] NULL,
	[airport_authority] [bit] NULL,
	[council_of_governments] [bit] NULL,
	[housing_authorities_public_tribal] [bit] NULL,
	[interstate_entity] [bit] NULL,
	[planning_commission] [bit] NULL,
	[port_authority] [bit] NULL,
	[transit_authority] [bit] NULL,
	[subchapter_scorporation] [bit] NULL,
	[limited_liability_corporation] [bit] NULL,
	[foreign_owned] [bit] NULL,
	[for_profit_organization] [bit] NULL,
	[nonprofit_organization] [bit] NULL,
	[other_not_for_profit_organization] [bit] NULL,
	[the_ability_one_program] [bit] NULL,
	[private_university_or_college] [bit] NULL,
	[state_controlled_institution_of_higher_learning] [bit] NULL,
	[1862_land_grant_college] [bit] NULL,
	[1890_land_grant_college] [bit] NULL,
	[1994_land_grant_college] [bit] NULL,
	[minority_institution] [bit] NULL,
	[historically_black_college] [bit] NULL,
	[tribal_college] [bit] NULL,
	[alaskan_native_servicing_institution] [bit] NULL,
	[native_hawaiian_servicing_institution] [bit] NULL,
	[school_of_forestry] [bit] NULL,
	[veterinary_college] [bit] NULL,
	[dot_certified_disadvantage] [bit] NULL,
	[self_certified_small_disadvantaged_business] [bit] NULL,
	[small_disadvantaged_business] [bit] NULL,
	[c8a_program_participant] [bit] NULL,
	[historically_underutilized_business_zone_hubzone_firm] [bit] NULL,
	[sba_certified_8a_joint_venture] [bit] NULL,
	[CSISmodifiedDate] [datetime2](7) NOT NULL,
	[CSIScreatedDate] [datetime2](7) NOT NULL,
	[current_total_value_of_award] [decimal](19, 4) NULL,
	[potential_total_value_of_award] [decimal](19, 4) NULL,
	[sam_exception_description] [varchar](255) NULL,
	[cage_code] [varchar](5) NULL,
	[award_or_idv_flag] [varchar](5) NULL,
	[inherently_governmental_functions] [varchar](10) NULL,
	[inherently_governmental_functions_description] [varchar](255) NULL,
	[organizational_type] [varchar](30) NULL,
	[total_dollars_obligated] [decimal](19, 4) NULL,
	[foreign_funding_description] [varchar](255) NULL,
	[contract_transaction_unique_key] [varchar](154) NULL,
	[contract_award_unique_key] [varchar](120) NULL,
	[solicitation_date] [date] NULL,
	[treasury_accounts_funding_this_award] [varchar](4000) NULL,
	[federal_accounts_funding_this_award] [varchar](1000) NULL,
	[highly_compensated_officer_1_name] [varchar](100) NULL,
	[highly_compensated_officer_1_amount] [decimal](19, 4) NULL,
	[highly_compensated_officer_2_name] [varchar](100) NULL,
	[highly_compensated_officer_2_amount] [decimal](19, 4) NULL,
	[highly_compensated_officer_3_name] [varchar](100) NULL,
	[highly_compensated_officer_3_amount] [decimal](19, 4) NULL,
	[highly_compensated_officer_4_name] [varchar](100) NULL,
	[highly_compensated_officer_4_amount] [decimal](19, 4) NULL,
	[highly_compensated_officer_5_name] [varchar](100) NULL,
	[highly_compensated_officer_5_amount] [decimal](19, 4) NULL,
	[usaspending_permalink] [varchar](150) NULL,
	[action_date_fiscal_year] [smallint] NULL,
	[disaster_emergency_fund_codes_for_overall_award] [varchar](500) NULL,
	[outlayed_amount_from_COVID-19_supplementals_for_overall_award] [decimal](19, 4) NULL,
	[obligated_amount_from_COVID-19_supplementals_for_overall_award] [decimal](19, 4) NULL,
	[object_classes_funding_this_award] [varchar](1000) NULL,
	[program_activities_funding_this_award] [varchar](5000) NULL,
	[recipient_county_name] [varchar](30) NULL,
	[recipient_uei] [varchar](12) NULL,
	[recipient_parent_uei] [varchar](12) NULL,
	[prime_award_base_transaction_description] [varchar](4008) NULL,
	[obligated_amount_from_IIJA_supplemental_for_overall_award] [decimal](19, 4) NULL,
	[outlayed_amount_from_IIJA_supplemental_for_overall_award] [decimal](19, 4) NULL,
	[recipient_name_raw] [nvarchar](150) NULL,
	[recipient_parent_name_raw] [nvarchar](150) NULL,
	[prime_award_transaction_recipient_county_fips_code] [int] NULL,
	[prime_award_transaction_recipient_state_fips_code] [tinyint] NULL,
	[prime_award_transaction_place_of_performance_county_fips_code] [int] NULL,
	[prime_award_transaction_place_of_performance_state_fips_code] [tinyint] NULL,
	[prime_award_transaction_recipient_cd_original] [varchar](22) NULL,
	[prime_award_transaction_place_of_performance_cd_original] [varchar](22) NULL,
	[total_outlayed_amount_for_overall_award] [decimal](19, 4) NULL,
	[USAspending_file_name] [varchar](255) NULL,
	[initial_report_date] [datetime2](7) NULL,
	[agency_id] [varchar](4) NULL,
	[correction_delete_ind] [varchar](255) NULL
) ON [PRIMARY]
GO

ALTER TABLE [ErrorLogging].[FPDSdelta] ADD  CONSTRAINT [DF__FPDSdelta2CSISmodifiedDate]  DEFAULT (getdate()) FOR [CSISmodifiedDate]
GO

ALTER TABLE [ErrorLogging].[FPDSdelta] ADD  CONSTRAINT [DF__FPDSdelta2CSIScreatedDate]  DEFAULT (getdate()) FOR [CSIScreatedDate]
GO


