SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ErrorLogging].[FAADSviolatesType](
	[unique_transaction_id] [varchar](255) NULL,
	[transaction_status] [varchar](255) NULL,
	[maj_agency_cat] [varchar](255) NULL,
	[account_title] [varchar](255) NULL,
	[rec_flag] [varchar](255) NULL,
	[fiscal_year] [varchar](255) NULL,
	[fyq] [varchar](255) NULL,
	[cfda_program_num] [varchar](255) NULL,
	[sai_number] [varchar](255) NULL,
	[recipient_name] [varchar](255) NULL,
	[recipient_city_code] [varchar](255) NULL,
	[recipient_city_name] [varchar](255) NULL,
	[recipient_county_code] [varchar](255) NULL,
	[recipient_county_name] [varchar](255) NULL,
	[recipient_zip] [varchar](255) NULL,
	[recipient_type] [varchar](255) NULL,
	[action_type] [varchar](255) NULL,
	[agency_code] [varchar](255) NULL,
	[federal_award_id] [varchar](255) NULL,
	[federal_award_mod] [varchar](255) NULL,
	[fed_funding_amount] [varchar](255) NULL,
	[non_fed_funding_amount] [varchar](255) NULL,
	[total_funding_amount] [varchar](255) NULL,
	[obligation_action_date] [varchar](255) NULL,
	[starting_date] [varchar](255) NULL,
	[ending_date] [varchar](255) NULL,
	[assistance_type] [varchar](255) NULL,
	[record_type] [varchar](255) NULL,
	[correction_late_ind] [varchar](255) NULL,
	[fyq_correction] [varchar](255) NULL,
	[principal_place_code] [varchar](255) NULL,
	[principal_place_state] [varchar](255) NULL,
	[principal_place_cc] [varchar](255) NULL,
	[principal_place_zip] [varchar](255) NULL,
	[principal_place_cd] [varchar](255) NULL,
	[cfda_program_title] [varchar](255) NULL,
	[agency_name] [varchar](255) NULL,
	[project_description] [varchar](300) NULL,
	[duns_no] [varchar](255) NULL,
	[duns_conf_code] [varchar](255) NULL,
	[progsrc_agen_code] [varchar](255) NULL,
	[progsrc_acnt_code] [varchar](255) NULL,
	[progsrc_subacnt_code] [varchar](255) NULL,
	[receip_addr1] [varchar](255) NULL,
	[receip_addr2] [varchar](255) NULL,
	[receip_addr3] [varchar](255) NULL,
	[face_loan_guran] [varchar](255) NULL,
	[orig_sub_guran] [varchar](255) NULL,
	[principal_place_state_code] [varchar](255) NULL,
	[recip_cat_type] [varchar](255) NULL,
	[asst_cat_type] [varchar](255) NULL,
	[recipient_cd] [varchar](255) NULL,
	[recipient_country_code] [varchar](255) NULL,
	[uri] [varchar](255) NULL,
	[recipient_state_code] [varchar](255) NULL,
	[CSISCreatedDate] [datetime] NOT NULL,
	[csismodifieddate] [datetime] NOT NULL,
	[principal_place_non_zip] [varchar](12) NULL,
	[exec1_fullname] [varchar](255) NULL,
	[exec1_amount] [varchar](255) NULL,
	[exec2_fullname] [varchar](255) NULL,
	[exec2_amount] [varchar](255) NULL,
	[exec3_fullname] [varchar](255) NULL,
	[exec3_amount] [varchar](255) NULL,
	[exec4_fullname] [varchar](255) NULL,
	[exec4_amount] [varchar](255) NULL,
	[exec5_fullname] [varchar](255) NULL,
	[exec5_amount] [varchar](255) NULL,
	[last_modified_date] [varchar](255) NULL,
	[principal_place_country_code] [varchar](255) NULL
) ON [PRIMARY]
GO
ALTER TABLE [ErrorLogging].[FAADSviolatesType] ADD  CONSTRAINT [DF_ERRORLOGGING_GRANTSviolatestype_CSISCreatedDate]  DEFAULT (getdate()) FOR [CSISCreatedDate]
GO
ALTER TABLE [ErrorLogging].[FAADSviolatesType] ADD  CONSTRAINT [DF_ERRORLOGGING_GRANTSviolatestype_CSISModifiedDate]  DEFAULT (getdate()) FOR [csismodifieddate]
GO
