SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ErrorLogging].[FPDSdeleted](
	[unique_transaction_id] [varchar](36) NULL,
	[transaction_status] [varchar](6) NULL,
	[obligatedamount] [decimal](19, 4) NULL,
	[baseandexercisedoptionsvalue] [decimal](19, 4) NULL,
	[baseandalloptionsvalue] [decimal](19, 4) NULL,
	[maj_agency_cat] [varchar](4) NULL,
	[mod_agency] [varchar](4) NULL,
	[maj_fund_agency_cat] [varchar](4) NULL,
	[contractingofficeagencyid] [varchar](4) NULL,
	[contractingofficeid] [varchar](6) NULL,
	[fundingrequestingagencyid] [varchar](4) NULL,
	[fundingrequestingofficeid] [varchar](6) NULL,
	[fundedbyforeignentity] [varchar](21) NULL,
	[signeddate] [date] NULL,
	[effectivedate] [date] NULL,
	[currentcompletiondate] [date] NULL,
	[ultimatecompletiondate] [date] NULL,
	[lastdatetoorder] [date] NULL,
	[contractactiontype] [varchar](41) NULL,
	[reasonformodification] [varchar](1) NULL,
	[typeofcontractpricing] [varchar](2) NULL,
	[priceevaluationpercentdifference] [smallint] NULL,
	[subcontractplan] [varchar](1) NULL,
	[lettercontract] [varchar](1) NULL,
	[multiyearcontract] [bit] NULL,
	[performancebasedservicecontract] [varchar](38) NULL,
	[majorprogramcode] [varchar](104) NULL,
	[contingencyhumanitarianpeacekeepingoperation] [varchar](1) NULL,
	[contractfinancing] [varchar](1) NULL,
	[costorpricingdata] [varchar](1) NULL,
	[costaccountingstandardsclause] [varchar](1) NULL,
	[descriptionofcontractrequirement] [varchar](4035) NULL,
	[purchasecardaspaymentmethod] [bit] NULL,
	[nationalinterestactioncode] [varchar](4) NULL,
	[progsourceagency] [varchar](2) NULL,
	[progsourceaccount] [varchar](4) NULL,
	[progsourcesubacct] [varchar](3) NULL,
	[account_title] [varchar](90) NULL,
	[rec_flag] [varchar](4) NULL,
	[typeofidc] [varchar](41) NULL,
	[multipleorsingleawardidc] [varchar](1) NULL,
	[programacronym] [varchar](29) NULL,
	[vendorname] [nvarchar](150) NULL,
	[vendoralternatename] [varchar](150) NULL,
	[vendorlegalorganizationname] [nvarchar](150) NULL,
	[vendordoingasbusinessname] [nvarchar](150) NULL,
	[divisionname] [nvarchar](150) NULL,
	[divisionnumberorofficecode] [varchar](10) NULL,
	[ccrexception] [varchar](70) NULL,
	[streetaddress] [varchar](100) NULL,
	[streetaddress2] [varchar](60) NULL,
	[streetaddress3] [varchar](55) NULL,
	[city] [varchar](35) NULL,
	[zipcode] [varchar](28) NULL,
	[vendorcountrycode] [nvarchar](50) NULL,
	[vendor_state_code] [varchar](30) NULL,
	[vendor_cd] [varchar](22) NULL,
	[vendorsitecode] [varchar](15) NULL,
	[vendoralternatesitecode] [varchar](20) NULL,
	[dunsnumber] [varchar](13) NULL,
	[parentdunsnumber] [varchar](13) NULL,
	[phoneno] [varchar](20) NULL,
	[faxno] [varchar](30) NULL,
	[registrationdate] [date] NULL,
	[renewaldate] [date] NULL,
	[mod_parent] [varchar](150) NULL,
	[locationcode] [varchar](9) NULL,
	[statecode] [varchar](2) NULL,
	[pop_state_code] [varchar](2) NULL,
	[placeofperformancecountrycode] [varchar](3) NULL,
	[placeofperformancezipcode] [varchar](10) NULL,
	[placeofperformancecongressionaldistrict] [varchar](6) NULL,
	[psc_cat] [varchar](2) NULL,
	[productorservicecode] [varchar](4) NULL,
	[systemequipmentcode] [varchar](4) NULL,
	[claimantprogramcode] [varchar](3) NULL,
	[principalnaicscode] [varchar](6) NULL,
	[informationtechnologycommercialitemcategory] [varchar](30) NULL,
	[gfe_gfp_code] [varchar](1) NULL,
	[useofepadesignatedproducts] [varchar](1) NULL,
	[recoveredmaterialclauses] [varchar](1) NULL,
	[seatransportation] [varchar](1) NULL,
	[contractbundling] [varchar](1) NULL,
	[consolidatedcontract] [varchar](1) NULL,
	[countryoforigin] [varchar](3) NULL,
	[placeofmanufacture] [varchar](1) NULL,
	[manufacturingorganizationtype] [varchar](1) NULL,
	[agencyid] [varchar](4) NULL,
	[piid] [varchar](50) NULL,
	[modnumber] [varchar](25) NULL,
	[transactionnumber] [bigint] NULL,
	[fiscal_year] [smallint] NULL,
	[idvagencyid] [varchar](4) NULL,
	[idvpiid] [varchar](50) NULL,
	[idvmodificationnumber] [varchar](25) NULL,
	[solicitationid] [varchar](69) NULL,
	[extentcompeted] [varchar](3) NULL,
	[reasonnotcompeted] [varchar](3) NULL,
	[numberofoffersreceived] [bigint] NULL,
	[commercialitemacquisitionprocedures] [varchar](1) NULL,
	[commercialitemtestprogram] [varchar](1) NULL,
	[smallbusinesscompetitivenessdemonstrationprogram] [varchar](6) NULL,
	[a76action] [varchar](3) NULL,
	[solicitationprocedures] [varchar](5) NULL,
	[typeofsetaside] [varchar](10) NULL,
	[localareasetaside] [varchar](4) NULL,
	[evaluatedpreference] [varchar](6) NULL,
	[fedbizopps] [varchar](1) NULL,
	[research_code] [varchar](3) NULL,
	[statutoryexceptiontofairopportunity] [varchar](4) NULL,
	[organizationaltype] [varchar](30) NULL,
	[firm8aflag] [bit] NULL,
	[hubzoneflag] [bit] NULL,
	[sdbflag] [bit] NULL,
	[issbacertifiedsmalldisadvantagedbusiness] [bit] NULL,
	[shelteredworkshopflag] [bit] NULL,
	[hbcuflag] [bit] NULL,
	[educationalinstitutionflag] [bit] NULL,
	[womenownedflag] [bit] NULL,
	[veteranownedflag] [bit] NULL,
	[srdvobflag] [bit] NULL,
	[localgovernmentflag] [bit] NULL,
	[minorityinstitutionflag] [bit] NULL,
	[aiobflag] [bit] NULL,
	[stategovernmentflag] [bit] NULL,
	[federalgovernmentflag] [bit] NULL,
	[minorityownedbusinessflag] [bit] NULL,
	[apaobflag] [bit] NULL,
	[tribalgovernmentflag] [bit] NULL,
	[baobflag] [bit] NULL,
	[naobflag] [bit] NULL,
	[saaobflag] [bit] NULL,
	[nonprofitorganizationflag] [bit] NULL,
	[isothernotforprofitorganization] [bit] NULL,
	[isforprofitorganization] [bit] NULL,
	[isfoundation] [bit] NULL,
	[haobflag] [bit] NULL,
	[ishispanicservicinginstitution] [bit] NULL,
	[emergingsmallbusinessflag] [bit] NULL,
	[hospitalflag] [bit] NULL,
	[contractingofficerbusinesssizedetermination] [varchar](1) NULL,
	[is1862landgrantcollege] [bit] NULL,
	[is1890landgrantcollege] [bit] NULL,
	[is1994landgrantcollege] [bit] NULL,
	[isveterinarycollege] [bit] NULL,
	[isveterinaryhospital] [bit] NULL,
	[isprivateuniversityorcollege] [bit] NULL,
	[isschoolofforestry] [bit] NULL,
	[isstatecontrolledinstitutionofhigherlearning] [bit] NULL,
	[receivescontracts] [bit] NULL,
	[receivesgrants] [bit] NULL,
	[receivescontractsandgrants] [bit] NULL,
	[isairportauthority] [bit] NULL,
	[iscouncilofgovernments] [bit] NULL,
	[ishousingauthoritiespublicortribal] [bit] NULL,
	[isinterstateentity] [bit] NULL,
	[isplanningcommission] [bit] NULL,
	[isportauthority] [bit] NULL,
	[istransitauthority] [bit] NULL,
	[issubchapterscorporation] [bit] NULL,
	[islimitedliabilitycorporation] [bit] NULL,
	[isforeignownedandlocated] [bit] NULL,
	[isarchitectureandengineering] [bit] NULL,
	[isdotcertifieddisadvantagedbusinessenterprise] [bit] NULL,
	[iscitylocalgovernment] [bit] NULL,
	[iscommunitydevelopedcorporationownedfirm] [bit] NULL,
	[iscommunitydevelopmentcorporation] [bit] NULL,
	[isconstructionfirm] [bit] NULL,
	[ismanufacturerofgoods] [bit] NULL,
	[iscorporateentitynottaxexempt] [bit] NULL,
	[iscountylocalgovernment] [bit] NULL,
	[isdomesticshelter] [bit] NULL,
	[isfederalgovernmentagency] [bit] NULL,
	[isfederallyfundedresearchanddevelopmentcorp] [bit] NULL,
	[isforeigngovernment] [bit] NULL,
	[isindiantribe] [bit] NULL,
	[isintermunicipallocalgovernment] [bit] NULL,
	[isinternationalorganization] [bit] NULL,
	[islaborsurplusareafirm] [bit] NULL,
	[islocalgovernmentowned] [bit] NULL,
	[ismunicipalitylocalgovernment] [bit] NULL,
	[isnativehawaiianownedorganizationorfirm] [bit] NULL,
	[isotherbusinessororganization] [bit] NULL,
	[isotherminorityowned] [bit] NULL,
	[ispartnershiporlimitedliabilitypartnership] [bit] NULL,
	[isschooldistrictlocalgovernment] [bit] NULL,
	[issmallagriculturalcooperative] [bit] NULL,
	[issoleproprietorship] [bit] NULL,
	[istownshiplocalgovernment] [bit] NULL,
	[istriballyownedfirm] [bit] NULL,
	[istribalcollege] [bit] NULL,
	[isalaskannativeownedcorporationorfirm] [bit] NULL,
	[iscorporateentitytaxexempt] [bit] NULL,
	[iswomenownedsmallbusiness] [bit] NULL,
	[isecondisadvwomenownedsmallbusiness] [bit] NULL,
	[isjointventurewomenownedsmallbusiness] [bit] NULL,
	[isjointventureecondisadvwomenownedsmallbusiness] [bit] NULL,
	[walshhealyact] [varchar](1) NULL,
	[servicecontractact] [varchar](1) NULL,
	[davisbaconact] [varchar](1) NULL,
	[clingercohenact] [bit] NULL,
	[otherstatutoryauthority] [varchar](1000) NULL,
	[interagencycontractingauthority] [varchar](3) NULL,
	[CSISCreatedDate] [datetime] NOT NULL,
	[CSISModifiedDate] [datetime] NOT NULL,
	[numberofactions] [bigint] NULL,
	[numberofemployees] [bigint] NULL,
	[annualrevenue] [decimal](19, 4) NULL,
	[CSIStransactionID] [int] NOT NULL,
	[PlaceofPerformanceCity] [varchar](100) NULL,
	[prime_awardee_executive1] [varchar](100) NULL,
	[prime_awardee_executive2] [varchar](100) NULL,
	[prime_awardee_executive3] [varchar](100) NULL,
	[prime_awardee_executive4] [varchar](100) NULL,
	[prime_awardee_executive5] [varchar](100) NULL,
	[prime_awardee_executive5_compensation] [decimal](19, 4) NULL,
	[prime_awardee_executive2_compensation] [decimal](19, 4) NULL,
	[prime_awardee_executive3_compensation] [decimal](19, 4) NULL,
	[prime_awardee_executive4_compensation] [decimal](19, 4) NULL,
	[prime_awardee_executive1_compensation] [decimal](19, 4) NULL,
	[last_modified_date] [datetime2](7) NULL,
	[TypeOfBusiness] [varchar](1) NULL,
	[ContractActionTypeDD350] [varchar](8) NULL,
	[headquartercode] [varchar](13) NULL,
	[CAGE] [varchar](5) NULL,
	[ContractNumber] [varchar](15) NULL,
	[award_type_code] [varchar](1) NULL,
	[idv_type_code] [varchar](1) NULL,
	[parent_award_type_code] [varchar](1) NULL,
	[parent_award_single_or_multiple_code] [varchar](1) NULL,
	[primary_place_of_performance_county_name] [varchar](22) NULL,
	[indian_tribe_federally_recognized] [bit] NULL,
	[other_minority_owned_business] [bit] NULL,
	[community_developed_corporation_owned_firm] [bit] NULL,
	[labor_surplus_area_firm] [bit] NULL,
	[city_local_government] [bit] NULL,
	[county_local_government] [bit] NULL,
	[inter_municipal_local_government] [bit] NULL,
	[local_government_owned] [bit] NULL,
	[corporate_entity_not_tax_exempt] [bit] NULL,
	[international_organization] [bit] NULL,
	[us_government_entity] [bit] NULL,
	[community_development_corporation] [bit] NULL,
	[domestic_shelter] [bit] NULL,
	[manufacturer_of_goods] [bit] NULL,
	[alaskan_native_servicing_institution] [bit] NULL,
	[native_hawaiian_servicing_institution] [bit] NULL,
	[sba_certified_8a_joint_venture] [bit] NULL,
	[dot_certified_disadvantage] [bit] NULL,
	[CSIStiebreakerID] [int] IDENTITY(1,1) NOT NULL,
	[contract_transaction_unique_key] [varchar](74) NULL,
	[contract_award_unique_key] [varchar](74) NULL,
	[current_total_value_of_award] [decimal](19, 4) NULL,
	[potential_total_value_of_award] [decimal](19, 4) NULL,
	[award_or_idv_flag] [varchar](5) NULL,
	[inherently_governmental_functions] [varchar](10) NULL,
	[total_dollars_obligated] [decimal](19, 4) NULL,
	[solicitation_date] [date] NULL,
	[treasury_accounts_funding_this_award] [varchar](4000) NULL,
	[federal_accounts_funding_this_award] [varchar](1000) NULL,
	[usaspending_permalink] [varchar](150) NULL,
	[awarding_agency_code] [smallint] NULL,
	[recipient_county_name] [varchar](30) NULL,
	[disaster_emergency_fund_codes_for_overall_award] [varchar](500) NULL,
	[object_classes_funding_this_award] [varchar](1000) NULL,
	[program_activities_funding_this_award] [varchar](4000) NULL,
	[obligated_amount_funded_by_COVID19_supplementals_for_overall_award] [decimal](19, 4) NULL,
	[outlayed_amount_funded_by_COVID19_supplementals_for_overall_award] [decimal](19, 4) NULL,
	[IsMissingFromUpdate] [bit] NOT NULL,
	[dod_acquisition_program_description] [varchar](255) NULL,
	[recipient_uei] [varchar](12) NULL,
	[recipient_parent_uei] [varchar](12) NULL
) ON [PRIMARY]
GO
ALTER TABLE [ErrorLogging].[FPDSdeleted] ADD  CONSTRAINT [df_CSISmodifiedDate]  DEFAULT (getdate()) FOR [CSISModifiedDate]
GO
ALTER TABLE [ErrorLogging].[FPDSdeleted] ADD  DEFAULT ((1)) FOR [IsMissingFromUpdate]
GO
ALTER TABLE [ErrorLogging].[FPDSdeleted]  WITH CHECK ADD  CONSTRAINT [fk_errorlogging_fpdsduplicates_csistransctionid] FOREIGN KEY([CSIStransactionID])
REFERENCES [Contract].[CSIStransactionID] ([CSIStransactionID])
GO
ALTER TABLE [ErrorLogging].[FPDSdeleted] CHECK CONSTRAINT [fk_errorlogging_fpdsduplicates_csistransctionid]
GO
