USE [CSIS360]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [FPDSTypeTable].[statecode](
	[Unseperated] [varchar](255) NULL,
	[statecode] [varchar](2) NOT NULL,
	[statecodeText] [nvarchar](255) NULL,
	[USA] [bit] NULL,
	[COCOM] [varchar](8) NULL,
 CONSTRAINT [statecode_key] PRIMARY KEY CLUSTERED 
(
	[statecode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
SET ANSI_PADDING OFF
GO
