USE [CSIS360]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [FPDSTypeTable].[walshhealyact](
	[Unseperated] [varchar](255) NULL,
	[walshhealyact] [varchar](1) NOT NULL,
	[walshhealyactText] [nvarchar](255) NULL,
 CONSTRAINT [PK_walshhealyact NO PK] PRIMARY KEY CLUSTERED 
(
	[walshhealyact] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
SET ANSI_PADDING OFF
GO
