USE [CSIS360]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FPDSTypeTable].[TypeOfIDC](
	[typeofIDC] [varchar](50) NULL,
	[typeOfIDCdescription] [varchar](50) NULL
) ON [PRIMARY]
GO
