USE [CSIS360]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FPDSTypeTable].[davisbaconact](
	[Unseperated] [varchar](255) NULL,
	[davisbaconact] [varchar](1) NOT NULL,
	[davisbaconactText] [nvarchar](255) NULL,
 CONSTRAINT [PK_davisbaconact] PRIMARY KEY CLUSTERED 
(
	[davisbaconact] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
