SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FPDSTypeTable].[ReferencedIDVTypeOfIDC NOT USING](
	[TypeOfIDC_code] [nvarchar](255) NULL,
	[TypeOfIDC_name] [nvarchar](255) NULL
) ON [PRIMARY]
GO
