SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FPDSTypeTable].[fedbizopps](
	[fedbizopps] [varchar](1) NOT NULL,
	[fed_biz_opps_name] [varchar](255) NULL,
 CONSTRAINT [pk_FPDStypetable_fedbizopps] PRIMARY KEY CLUSTERED 
(
	[fedbizopps] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
