SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FPDSTypeTable].[gfe_gfp](
	[Unseperated] [varchar](255) NULL,
	[gfe_gfp] [varchar](1) NOT NULL,
	[gfe_gfpText] [nvarchar](255) NULL,
 CONSTRAINT [gfe_gfp_key] PRIMARY KEY CLUSTERED 
(
	[gfe_gfp] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
