SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Location].[State_FIPS_Code](
	[state_fips_code] [tinyint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [Location].[State_FIPS_Code] ADD  CONSTRAINT [pk_location_state_fips_code] PRIMARY KEY CLUSTERED 
(
	[state_fips_code] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
