SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ProductOrServiceCode].[CrisisProductOrServiceArea](
	[CrisisProductOrServiceArea] [varchar](28) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CrisisProductOrServiceArea] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
