USE [CSIS360]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ProductOrServiceCode].[ServicesCategory](
	[ServicesCategory] [varchar](28) NOT NULL,
	[SimpleBucket] [nvarchar](255) NULL,
	[IsService] [bit] NULL,
 CONSTRAINT [PK__Services__88EA51992E9A2CA2] PRIMARY KEY CLUSTERED 
(
	[ServicesCategory] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
