SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ProductOrServiceCode].[CanadaSector](
	[CanadaSector] [nvarchar](75) NOT NULL,
 CONSTRAINT [PK__CanadaSe__5FF668C41DAEDE69] PRIMARY KEY CLUSTERED 
(
	[CanadaSector] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
