SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ProductOrServiceCode].[HostNation3Category](
	[HostNation3Category] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[HostNation3Category] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
