SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ProductOrServiceCode].[ProductServiceOrRnDarea](
	[ProductServiceOrRnDarea] [varchar](49) NOT NULL,
	[RnD_BudgetActivity] [varchar](100) NULL,
 CONSTRAINT [pk_ProductServiceOrRnDarea] PRIMARY KEY CLUSTERED 
(
	[ProductServiceOrRnDarea] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
