SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ProductOrServiceCode].[ServicesCategory](
	[ServicesCategory] [varchar](28) NOT NULL,
	[SimpleBucket] [nvarchar](255) NULL,
	[IsService] [bit] NULL,
 CONSTRAINT [PK__Services__88EA51992E9A2CA2] PRIMARY KEY CLUSTERED 
(
	[ServicesCategory] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
