USE [CSIS360]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ProductOrServiceCode].[CanadaSector](
	[CanadaSector] [nvarchar](75) NOT NULL,
 CONSTRAINT [PK__CanadaSe__5FF668C41DAEDE69] PRIMARY KEY CLUSTERED 
(
	[CanadaSector] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
