USE [CSIS360]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Project].[RANDID](
	[RANDID] [varchar](50) NOT NULL,
	[Service] [varchar](50) NULL,
	[Weapon Type] [varchar](50) NULL,
	[Contractor] [varchar](50) NULL,
	[Prototype] [varchar](50) NULL,
	[Confidence] [varchar](50) NULL,
	[Prototyping Phase] [varchar](50) NULL,
	[Precedent] [varchar](50) NULL,
	[Modification] [varchar](50) NULL,
	[Year of Program Initiation] [varchar](50) NULL,
	[Year of Development Start] [varchar](50) NULL,
	[Year of Production Start] [varchar](50) NULL,
	[Years Past Program Initiation] [varchar](50) NULL,
	[Years Past Development Start] [varchar](50) NULL,
	[Years Past Production Start] [varchar](50) NULL,
	[MS 1 (actual)] [varchar](50) NULL,
	[MS 2 (plan)] [varchar](50) NULL,
	[MS 2 (actual)] [varchar](50) NULL,
	[MS 3a (actual)] [varchar](50) NULL,
	[Initial Operational Delivery (plan)] [varchar](50) NULL,
	[Initial Operational Delivery (actual)] [varchar](50) NULL,
	[IOT&E Start (plan)] [varchar](50) NULL,
	[IOT&E Start (actual)] [varchar](50) NULL,
	[IOT&E Complete (plan)] [varchar](50) NULL,
	[IOT&E Complete (actual)] [varchar](50) NULL,
	[Phase 1 Length (plan)] [varchar](50) NULL,
	[Phase 1 Length (actual)] [varchar](50) NULL,
	[Phase 2 Length (plan)] [varchar](50) NULL,
	[Phase 2 Length (actual)] [varchar](50) NULL,
	[Total Program Length (plan)] [varchar](50) NULL,
	[Total Program Length (actual)] [varchar](50) NULL,
	[Phase 1 Slip] [varchar](50) NULL,
	[Phase 2 Slip] [varchar](50) NULL,
	[Total Program Slip] [varchar](50) NULL,
	[Percentage Slip in Phase 1] [varchar](50) NULL,
	[Percentage Slip in Phase 2] [varchar](50) NULL,
	[Percentage Total Program Slip] [varchar](50) NULL,
	[Ratio Phase 1  Phase 2 Length (plan)] [varchar](50) NULL,
	[Ratio Phase 1  Phase 2 Length (actual)] [varchar](50) NULL,
	[Slip in IOT&E] [varchar](50) NULL,
	[Concurrency Measure (percentage)] [varchar](50) NULL,
	[Concurrency Measure (interval)] [varchar](50) NULL,
	[Develop] [varchar](50) NULL,
	[Unadj Proc] [varchar](50) NULL,
	[Adj proc PE Baseline ] [varchar](50) NULL,
	[Adj proc DE Baseline ] [varchar](50) NULL,
	[Adj proc PdE Baseline ] [varchar](50) NULL,
	[MILCON] [varchar](50) NULL,
	[Develop_2] [varchar](50) NULL,
	[Proc] [varchar](50) NULL,
	[MILCON_2] [varchar](50) NULL,
	[Total] [varchar](50) NULL,
	[Develop Cost Growth Factor] [varchar](50) NULL,
	[Unadj Proc Cost Growth Factor] [varchar](50) NULL,
	[Adj Proc Cost Growth Factor] [varchar](50) NULL,
	[Total Program Cost Growth Factor] [varchar](50) NULL,
	[Develop_3] [varchar](50) NULL,
	[Proc_2] [varchar](50) NULL,
	[MILCON_3] [varchar](50) NULL,
	[Total_2] [varchar](50) NULL,
	[Develop Cost Growth Factor_2] [varchar](50) NULL,
	[Unadj Proc Cost Growth Factor_2] [varchar](50) NULL,
	[Adj Proc Cost Growth Factor_2] [varchar](50) NULL,
	[Total Program Cost Growth Factor_2] [varchar](50) NULL,
	[Develop_4] [varchar](50) NULL,
	[Proc_3] [varchar](50) NULL,
	[MILCON_4] [varchar](50) NULL,
	[Total_3] [varchar](50) NULL,
	[Develop Cost Growth Factor_3] [varchar](50) NULL,
	[Unadj Proc Cost Growth Factor_3] [varchar](50) NULL,
	[Adj Proc Cost Growth Factor_3] [varchar](50) NULL,
	[Total Program Cost Growth Factor_3] [varchar](50) NULL,
	[Ratio   Devel$   Proc$   (PE)] [varchar](50) NULL,
	[Ratio   Devel$   Proc$   (DE)] [varchar](50) NULL,
	[Ratio   Devel$   Proc$ (PdE)] [varchar](50) NULL,
	[Ratio   Devel$   Proc$    (CE-PE)] [varchar](50) NULL,
	[Ratio   Devel$   Proc$     (CE-DE)] [varchar](50) NULL,
	[Ratio   Devel$   Proc$     (CE-PdE)] [varchar](50) NULL,
	[PE Baseline] [varchar](50) NULL,
	[DE Baseline] [varchar](50) NULL,
	[PdE Baseline] [varchar](50) NULL,
	[Current] [varchar](50) NULL,
	[CE-PE] [varchar](50) NULL,
	[CE-DE] [varchar](50) NULL,
	[CE-PdE] [varchar](50) NULL,
	[ProjectID] [int] NULL,
 CONSTRAINT [pk_RANDID] PRIMARY KEY CLUSTERED 
(
	[RANDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
