SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Project].[IB_Trends26_Table](
	[fiscal_year] [smallint] NULL,
	[contract_transaction_unique_key] [varchar](154) NULL,
	[contract_award_unique_key] [varchar](120) NULL,
	[signeddate] [date] NULL,
	[effectivedate] [date] NULL,
	[UnmodifiedUltimateDurationCategory] [varchar](12) NOT NULL,
	[CurrentDurationCategory] [varchar](12) NOT NULL,
	[city] [varchar](35) NULL,
	[vendorcountrycode] [nvarchar](50) NULL,
	[vendor_state_code] [varchar](35) NULL,
	[placeofperformancecountrycode] [varchar](3) NULL,
	[prime_award_transaction_place_of_performance_state_fips_code] [tinyint] NULL,
	[prime_award_transaction_place_of_performance_county_fips_code] [int] NULL,
	[placeofmanufacture] [varchar](8) NOT NULL,
	[ManufacturingOrganizationText_sum] [varchar](60) NULL,
	[PlaceofPerformanceCity] [varchar](100) NULL,
	[primary_place_of_performance_county_name] [varchar](30) NULL,
	[CompetitionClassification] [varchar](78) NULL,
	[obligatedAmount] [decimal](19, 4) NULL,
	[numberOfActions] [bigint] NULL,
	[obligatedAmount_25USD] [float] NULL,
	[TypeOfContractPricingText] [nvarchar](255) NULL,
	[TypeOfContractPricing5Category] [nvarchar](50) NULL,
	[PricingUCA] [varchar](20) NULL,
	[recipient_uei] [varchar](12) NULL,
	[recipient_parent_uei] [varchar](12) NULL,
	[vendorname] [nvarchar](150) NULL,
	[emergingsmallbusinessflag] [bit] NULL,
	[IsEntityTraditional] [tinyint] NULL,
	[VendorSize] [varchar](34) NOT NULL,
	[VendorSize_5] [varchar](9) NOT NULL,
	[ContractingCustomer] [nvarchar](50) NULL,
	[ContractingIsDefense] [bit] NULL,
	[ContractingSubCustomer] [nvarchar](50) NULL,
	[ContractingAgencyText] [nvarchar](255) NULL,
	[ContractingOfficeName] [nvarchar](255) NULL,
	[Simple] [varchar](8) NULL,
	[ProductOrServiceArea] [varchar](28) NULL,
	[ProductOrServiceCodeText] [varchar](255) NULL,
	[PlatformPortfolio] [varchar](30) NULL,
	[majorprogramcode] [varchar](104) NOT NULL,
	[IsFMS] [int] NOT NULL,
	[ContractSize] [varchar](11) NOT NULL,
	[OMB25_Deflator] [float] NULL,
	[Duration_Days] [int] NULL,
	[AvgObligationPerAction] [decimal](38, 23) NULL
) ON [PRIMARY]
GO
