SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Project].[DBAcategory](
	[DBAcategory] [varchar](31) NOT NULL,
 CONSTRAINT [pk_budget_ProcurementCategory] PRIMARY KEY CLUSTERED 
(
	[DBAcategory] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
