SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Project].[DBAcategory](
	[DBAcategory] [varchar](31) NOT NULL,
 CONSTRAINT [pk_budget_ProcurementCategory] PRIMARY KEY CLUSTERED 
(
	[DBAcategory] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
