SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Vendor].[OrganizationalType](
	[OrganizationalType] [varchar](30) NOT NULL,
 CONSTRAINT [pk_Vendor_OrganizationalType] PRIMARY KEY CLUSTERED 
(
	[OrganizationalType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
