SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Vendor].[OrganizationalType](
	[OrganizationalType] [varchar](30) NOT NULL,
 CONSTRAINT [pk_Vendor_OrganizationalType] PRIMARY KEY CLUSTERED 
(
	[OrganizationalType] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
